src/Entity/Numbers.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\NumbersRepository")
 */
class Numbers
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\NotBlank
     * @Assert\Range(
     *     min = 1,
     *     max = 99999,
     * )
     */
    private $inputNumber;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $createdAt;

    public function __construct()
    {
        $this->createdAt = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getResult(): ?int
    {
        $indexArray = array_fill(0, $inputNumber = $this->inputNumber + 1, null);
        foreach ($indexArray as $index => $value) {
            switch ($index) {
                case 0:
                    $indexArray[$index] = 0;
                    break;
                case 1:
                    $indexArray[$index] = 1;
                    break;
                case $index % 2 === 0:
                    $indexArray[$index] = $indexArray[$index / 2];
                    break;
                case $index % 2 !== 0:
                    $i = ($index - 1) / 2;
                    $indexArray[$index] = $indexArray[$i] + $indexArray[$i + 1];
            }
        }

        return max($indexArray);
    }

    public function getInputNumber(): ?int
    {
        return $this->inputNumber;
    }

    public function setInputNumber(?int $inputNumber): self
    {
        $this->inputNumber = $inputNumber;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function __toString()
    {
        return $this->getCreatedAt()->format('Y-m-d H:i:s').', '.$this->getInputNumber().', '.$this->getResult();
    }

}

src/Form/NumbersType.php
<?php

namespace App\Form;

use App\Entity\Numbers;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Length;

class NumbersType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('inputNumber',null, [
                'label' => 'Podaj liczbę przedstawiającą wielkość zbioru',
                'attr' => [
                    'min' => 1,
                    'max' => 99999,
                    'oninvalid'=>"setCustomValidity('Proszę podać numer z zakresu od 1 do 99999')"
                ]
            ])
            ->add('submit', SubmitType::class, [
                'label' => 'Zapisz',
                'attr' => [
                    'class' => 'btn btn-primary',
                    'required',
                ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Numbers::class,
        ]);
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Entity\Numbers;
use App\Form\NumbersType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;

class MainController extends AbstractController
{

    /**
     * @Route("/", name="main")
     * @param EntityManagerInterface $em
     * @param Request $request
     * @return Response
     */
    public function index(EntityManagerInterface $em, Request $request)
    {
        $form = $this->createForm(NumbersType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $numbers = $form->getData();
            $em->persist($numbers);
            $em->flush();
            $this->addFlash('success', 'Wielkosc zbioru: '.$numbers->getInputNumber().' maksymalna wartosc w zbiorze: '.$numbers->getResult());

            return $this->redirectToRoute('main');
        }

        return $this->render('main/index.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/list", name="list")
     */
    public function numbersList()
    {
        $allNumbers = $this->getDoctrine()->getRepository(Numbers::class)->findAllDesc();

        return $this->render('main/numbersList.html.twig', ['allNumbers' => $allNumbers]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
            <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        {% endblock %}
    </body>
</html>

templates/main/helper/modal.html.twig
<div class="modal fade" id="form" tabindex="-1" role="dialog" aria-labelledby="form" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Podaj liczbe </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                {{ form(form) }}
            </div>
        </div>
    </div>
</div>

templates/main/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liczby{% endblock %}

{% block body %}
    <div class="jumbotron">
        <div class="container">
            <h1 class="display-4">Witam w aplikacji tworzącej ciągi liczb</h1>
            <p class="lead">Jest to prosta aplikacja w której podając wielkość zbioru otrzymasz najwyższą wartość w ciągu liczb</p>
            <p>Zbiór przedstawia sie następująco dla podanych indexów zbioru:</p>
            <ul>
                <li> Dla indexu 0 wynik jest równy 0</li>
                <li> Dla indexu 1  wynik jest równy 1</li>
                <li> Dla indexów parzystych wynik jest równy wartości indexu podzielonej przez 2</li>
                <li> Dla indexów nieparzystych wynik jest równy (wartości indexu minus 1) podzielonej przez 2 plus (wartości indeksu podzielonej przez 2) plus 1</li>
            </ul>
            <hr class="my-4">
        </div>

        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <p>Przejdz do formularza</p>
                    <button type="button" data-toggle="modal" data-target="#form" class="btn btn-primary btn-lg" href="#form" role="button">Formularz</button>
                </div>
                <div class="col-sm-6">
                    <p>Historia zapytań</p>
                    <button class="btn btn-primary btn-lg" id="button-list" >Historia</button>
                </div>
            </div>
        </div>
    </div>
    {% for message in app.flashes('success') %}
        <div class="alert alert-success">

            <div class="card">
                <div class="card-body">
                    <blockquote class="blockquote mb-0">
                        <p>{{ message }}</p>
                    </blockquote>
                </div>
            </div>
        </div>
    {% endfor %}
    {% include 'main/helper/modal.html.twig' %}
    <div id="list" class="visible">
        {{ render(controller('App\\Controller\\MainController::numbersList')) }}
    </div>
{% endblock %}

templates/main/numbersList.html.twig
<ul class="list-group">
    {% for number in allNumbers %}
            <li class="list-group-item">Sprawdzono: {{ number.createdAt| date }}: <br> Wielkość zbioru: {{ number.inputNumber }} najwyższa wartość: <b>{{ number.result }}</b></li>
    {% endfor %}
    {% if allNumbers is empty %}
        <li class="list-group-item">Brak rekordów</li>
    {% endif %}
</ul>